//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionFichersApp.Databases
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestionFichiersEntities : DbContext
    {
        public GestionFichiersEntities()
            : base("name=GestionFichiersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fichier> Fichier { get; set; }
        public virtual DbSet<Personne> Personne { get; set; }
        public virtual DbSet<PersonneFichier> PersonneFichier { get; set; }
        public virtual DbSet<Type> Type { get; set; }
    }
}
