//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionFichersApp.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonneFichier
    {
        public long Personne { get; set; }
        public long Fichier { get; set; }
        public Nullable<System.DateTime> DateLecture { get; set; }
        public Nullable<int> Note { get; set; }
        public string Commentaire { get; set; }
    
        public virtual Fichier Fichier1 { get; set; }
        public virtual Personne Personne1 { get; set; }
    }
}
